import type { Metadata } from "next";
import { Geist as FontSans } from "next/font/google";
import "./globals.css";

import { Toaster } from "@/components/ui/sonner";

import { cn } from "@/lib/utils";
import Header from "@/components/header";

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(" font-sans antialiased bg-gray-100", fontSans.variable)}
			>
				<div className="max-w-screen-lg mx-auto p-4">
					<Header />
					{children}
				</div>
				<Toaster />
			</body>
		</html>
	);
}
